from __future__ import annotations

from collections import defaultdict
from dataclasses import dataclass
from datetime import datetime
from typing import Dict, Iterable, Protocol

from .domain import Candle, Fill, Order, Signal, Side
from .execution import ExecutionSimulator
from .portfolio import Portfolio, PortfolioSnapshot
from .risk import RiskManager


class Strategy(Protocol):
    def on_bar(self, candle: Candle, history: list[Candle]) -> Signal | None: ...


@dataclass(frozen=True)
class SimulationResult:
    snapshots: list[PortfolioSnapshot]
    fills: list[Fill]
    rejected_signals: list[tuple[datetime, str, str]]


class Simulator:
    """The single source of truth for historical simulation and replay."""

    def __init__(self, initial_capital: float, strategy: Strategy, risk: RiskManager | None = None, execution: ExecutionSimulator | None = None) -> None:
        self.execution = execution or ExecutionSimulator()
        self.portfolio = Portfolio(initial_capital, self.execution)
        self.strategy = strategy
        self.risk = risk or RiskManager()
        self.pending: Dict[str, Order] = {}
        self.history: Dict[str, list[Candle]] = defaultdict(list)
        self.prices: Dict[str, float] = {}
        self.snapshots: list[PortfolioSnapshot] = []
        self.fills: list[Fill] = []
        self.rejected: list[tuple[datetime, str, str]] = []

    def process(self, candles: Iterable[Candle]) -> None:
        batch = sorted(candles, key=lambda c: (c.timestamp, c.symbol))
        if not batch:
            return
        timestamp = batch[0].timestamp
        if any(c.timestamp != timestamp for c in batch):
            raise ValueError("Simulator.process requires candles sharing one timestamp")

        # 1. Mark the market and resolve exits using the current candle range.
        for candle in batch:
            self.prices[candle.symbol] = candle.close
            position = self.portfolio.positions.get(candle.symbol)
            if position:
                exit_fill = self.execution.exit_fill(position, candle)
                if exit_fill:
                    self.portfolio.apply_exit(exit_fill)
                    self.fills.append(exit_fill)

        # 2. Fill orders generated by the previous completed bar at this open.
        for candle in batch:
            order = self.pending.pop(candle.symbol, None)
            if order and candle.symbol not in self.portfolio.positions:
                fill = self.execution.entry_fill(order, candle)
                self.portfolio.apply_entry(fill, order.stop_loss, order.target)
                self.fills.append(fill)
                self.prices[candle.symbol] = candle.close

        # 3. Only after the candle is complete may strategy logic observe it.
        for candle in batch:
            history = self.history[candle.symbol]
            signal = self.strategy.on_bar(candle, history)
            history.append(candle)
            if signal is None or candle.symbol in self.portfolio.positions or candle.symbol in self.pending:
                continue
            decision = self.risk.evaluate(
                signal,
                equity=self.portfolio.equity(self.prices),
                open_positions=self.portfolio.open_positions(),
                current_price=candle.close,
            )
            if not decision.approved:
                self.rejected.append((timestamp, candle.symbol, decision.reason or "rejected"))
                continue
            self.pending[candle.symbol] = Order(
                candle.symbol, signal.side, decision.quantity, timestamp,
                signal.strategy, signal.stop_loss, signal.target
            )

        self.portfolio.assert_invariants(self.prices)
        self.snapshots.append(PortfolioSnapshot(
            timestamp,
            self.portfolio.cash,
            self.portfolio.equity(self.prices),
            self.portfolio.realized_pnl,
            self.portfolio.unrealized_pnl(self.prices),
            self.portfolio.open_positions(),
        ))

    def result(self) -> SimulationResult:
        return SimulationResult(self.snapshots, self.fills, self.rejected)
